#!/bin/bash

which_cmd() {
        local block=1
        if [ "a${1}" = "a-n" ]
        then
                local block=0
                shift
        fi

        unalias $2 >/dev/null 2>&1
        local cmd=`which $2 2>/dev/null | head -n 1`
        if [ $? -gt 0 -o ! -x "${cmd}" ]
        then
                if [ ${block} -eq 1 ]
                then
                        echo >&2
                        echo >&2 "ERROR:        Command '$2' not found in the system path."
                        echo >&2 "      WPDoc requires this command for its operation."
                        echo >&2 "      Please install the required package and retry."
                        echo >&2
                        echo >&2 "      which $2"
                        exit 1
                fi
                return 1
        fi
        
        eval $1=${cmd}
        return 0
}

# Commands that are mandatory for WPDoc operation:
which_cmd CP_CMD cp
which_cmd SED_CMD sed
which_cmd GIT_CMD git
which_cmd CURL_CMD curl
which_cmd WGET_CMD wget
which_cmd PHP_CMD php

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -d|--dir)
    DIRECTORY="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
done

if [ -a "wp-cli.phar" ]
then
        echo "SUCCESS."
        VERSION=$($PHP_CMD wp-cli.phar core version --path=$DIRECTORY)
        echo "WordPress Version: " ${VERSION}
else
        echo "ERROR."
        exit 1
fi